### ISSUE TITLE
Login and signup page 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Note-Vault/Note-Vault#1]
Hi there, i am Ram👋
I can add login and signup page with full backend 
assign the task to me

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by anuni03** [comment]
I believe that i will able to make whole sign up and log in with animations please assign me this issue under GSSOC 2024

**Comment by khadesamrudhi** [comment]
please assign me this issue.

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by SumitKumar-17** [comment]
@kshavp  I want to work on this ssue. Can you assign this issue to me under GSSoc'24?

**Comment by ManpreetSingh18** [comment]
I want to work on this ssue. Can you assign this issue to me under GSSoc'24?
**My Propsal**
1. **Signup & Login:** Develop user registration and login pages.
2. **Password Security:** Use bcrypt for secure password hashing.
3. **JWT Token Management:** Generate and store tokens securely.
4. **Error Handling:** Provide graceful feedback on authentication errors.
5. **API Security:** Verify JWT tokens for endpoint access control.
6. **Database:"" Will use Atlas mongo db cloud storage

 Interested in GSSoC, prior experience in similar projects made using mern stack ([GitHub](https://github.com/ManpreetSingh18/tavPrasad)) and also one other project made without react and db store on atlas cloud [-](https://physeria-full.onrender.com/)

**Comment by goyalh4164** [comment]
Login and SignUp page already exist in our project...if you want to modify it you can raise another issue
