### ISSUE TITLE
Feat: New UI for the Note Card

### ISSUE THREAD

**Issue by SanchitGeez** [Note-Vault/Note-Vault#102]
### Describe the feature

I think the current Card component looks very cluttered ....I have tried to make it more minimal and modern. 
Can you please assign me this Issue under GSSOC.

### Add ScreenShots

![newNoteDesign](https://github.com/Note-Vault/Note-Vault/assets/106537325/fc9959f7-b6c9-486c-8992-d4c3ffcc1635)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hi!! I am Anshdeep singh, contributor in GSSoC'24. I would like to address this issue and make the respective changes.

**Comment by VaibhavArora314** [comment]
#111
