### ISSUE TITLE
BUG: Add Restriction to special characters in the name field.

### ISSUE THREAD

**Issue by goyalh4164** [Note-Vault/Note-Vault#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have seen some of the users are able to add special characters in the name field like (,@,#) we only want upper or lower case letters in this field .. anyone how can solve this can add the approach we will assign to that person

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by BHS-Harish** [comment]
Hey @goyalh4164 

Please assign to me
Let me fix it
