### ISSUE TITLE
BUG: Updation in Signup and Login Page

### ISSUE THREAD

**Issue by BHS-Harish** [Note-Vault/Note-Vault#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Both the signup and login page contains extra space in the right side that's scrollable.

**Screen shot**
![image](https://github.com/Note-Vault/Note-Vault/assets/114602603/068bf02b-757c-41a1-a1cd-543c4e0f9dea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BHS-Harish** [comment]
Hey @goyalh4164 

I would like to solve the issue.
please assign to me

Thanks in advance

**Comment by anshdeep0504** [comment]
Hi!! I am Anshdeep singh, contributor in GSSoC'24. I would like to address this issue and make the respective changes.
