### ISSUE TITLE
BUG: Text Overflow in dark and light mode button

### ISSUE THREAD

**Issue by BHS-Harish** [Note-Vault/Note-Vault#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text was overflowed from the button in dark and light mode.
Either we can fix it and remove it and add icon for them

**Screen shot**

![image](https://github.com/Note-Vault/Note-Vault/assets/114602603/b74badc5-fe12-424f-bc97-aea12f82396c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hi!! I am Anshdeep singh, contributor in GSSoC'24. I would like to address this issue and make the respective changes.
