### ISSUE TITLE
Add screenshots of the project in the README.md

### ISSUE THREAD

**Issue by VaibhavArora314** [Note-Vault/Note-Vault#11]
Add screenshots of the working project in README.md

**Comment by alishasingh06** [comment]
@VaibhavArora314  I want to contribute to this issue, please assign.
Also, please provide the correct deployment link for the website, the one mentioned in Readme file is incorrect.

**Comment by VaibhavArora314** [comment]
the deployment link is now added in the project's description.

**Comment by alishasingh06** [comment]
@VaibhavArora314 kindly close this issue, it's completed
