### ISSUE TITLE
BUG: Adding Zod Validation to the File

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [Note-Vault/Note-Vault#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@goyalh4164 Hello Sir, there is no Zod Validation in the project . Because of which any one can add any type of Username and Password which make security low.

![image](https://github.com/Note-Vault/Note-Vault/assets/122930278/71abaf2b-b6c1-4a56-bdd6-256ac20d27aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ujjwalagrawal-1** [comment]
@goyalh4164 Please Allow me to create a Zod Schema and add validation to the Project.

please assign this issue to me

**Comment by imkeertiag** [comment]
@Ultimateutkarsh11 Can you Please Assign this issue to me as @ujjwalagrawal-1 is already taking very much time
