### ISSUE TITLE
Feat: Home Page an be improved 

### ISSUE THREAD

**Issue by Aanyaa26** [Note-Vault/Note-Vault#114]
### Describe the feature

The home page is not at all attractive moreover can be enhanced by improving its CSS. The colours and the content written can be improved significantly!

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/128315909/62181457-18dd-4ded-95e3-3a0662712ae3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyagaut** [comment]
@Ultimateutkarsh11 i want to work on this issue please assign to me

**Comment by drick-infinity** [comment]
assign this issue to me under gssoc'24 
i want to contribute
how do i run on my pc 
its not working on running npm run dev or npm start

**Comment by harshcodesit** [comment]
Hi @techmannih
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .
