### ISSUE TITLE
Feat: A proper Navbar must be included

### ISSUE THREAD

**Issue by Aanyaa26** [Note-Vault/Note-Vault#115]
### Describe the feature

The navbar is one of the most important features of any website. In this site navbar is not properly defined and leads to some missing elements on the home page. 
I can modify the navbar effectively with proper CSS. Please permit me!

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/128315909/c4eac7ef-8894-49c9-a43e-e9e21f9dcf98)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PuR-vI** [comment]
I'd like to work on this. please assign this issue to me under GSSOC'24
