### ISSUE TITLE
No about us page

### ISSUE THREAD

**Issue by NitinChakrawarti** [Note-Vault/Note-Vault#116]
### Describe the feature

Currently website doesn't have any about us page, and about page for a website is must thing it is necessary for website this website user can know more about NoteVault .

@VaibhavArora314  please assign this issue to me under GSSoC'24 I want to contribute in this project.

Thankyou.

### Add ScreenShots

![Screenshot 2024-05-15 122708](https://github.com/Note-Vault/Note-Vault/assets/149225785/eb62ef23-bfd3-468c-96e7-176d39f311a1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
This issue has already been assigned to someone else (Issue #91).
