### ISSUE TITLE
Add Topics 

### ISSUE THREAD

**Issue by Princegupta101** [Note-Vault/Note-Vault#13]
In GSSoC'24, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue. 👍

**Comment by alishasingh06** [comment]
@goyalh4164 kindly assign me the issue if this needs to be done.

**Comment by dakshsinghrathore** [comment]
@alishasingh06 Actually am a fellow contributor just like you not admin😄

**Comment by Ultimateutkarsh11** [comment]
@Princegupta101 the idea seems good, but github topics can only be edited by the admins of the repository.

**Comment by alishasingh06** [comment]
> @alishasingh06 Actually am a fellow contributor just like you not admin😄

ohh alright :)
