### ISSUE TITLE
Feat: Redesign Landing Page

### ISSUE THREAD

**Issue by hars-21** [Note-Vault/Note-Vault#131]
### Describe the feature

I want to fully redesign the landing page of the website with scrolling animations.
Providing an amazing user interface and improve user experience 
Fully designing the home page of the site.
Changing simple bootstrap with animations.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anu03k** [comment]
I seee that that page is still the same. I would like to use a different color paltelle , font and adjust the text in the landing page to redesign it. I am an expert it ui design and frontened. Further I am GsSOC 24 contributer. I would like to work in  this issue

**Comment by goyalh4164** [comment]
see the latest page color template is now changed

**Comment by hars-21** [comment]
No I want don't want to change colour, i will add animations and completely redesign with fixed navbar, animations, new theme
