### ISSUE TITLE
Feat:Redesign NoteVault Cards

### ISSUE THREAD

**Issue by PuR-vI** [Note-Vault/Note-Vault#132]
### Describe the feature

I'd like to redesign and properly apply suitable fonts and card views to this section to make it look more professional and user friendly. Please assign this issue to me under GSSOC'24

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/97090750/91953544-0d2e-40df-a578-3a98746f7d77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PuR-vI** [comment]
remote: Permission to Note-Vault/Note-Vault.git denied to PuR-vI.
fatal: unable to access 'https://github.com/Note-Vault/Note-Vault.git/': The requested URL returned error

im facing this error while i push my branch . how can i resolve this

**Comment by Ultimateutkarsh11** [comment]
@PuR-vI you have cloned the original repository, try creating a fork of the original repository and clone it.
After that, do your required changes and try to push the code.

**Comment by PuR-vI** [comment]
Okay thankyou I'll complete this soon. Sorry for the delay.

**Comment by Ultimateutkarsh11** [comment]
No issues, take your time.
