### ISSUE TITLE
Navbar Ui to be updated

### ISSUE THREAD

**Issue by Nehakumari1208** [Note-Vault/Note-Vault#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

No proper alignment 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nehakumari1208** [comment]
Assign me this issue

**Comment by goyalh4164** [comment]
@Nehakumari1208 post any better design that you can make .. then our team will review it and assign to you
