### ISSUE TITLE
Feat:  adding password hide and show functionality in register page

### ISSUE THREAD

**Issue by piyush-gpt** [Note-Vault/Note-Vault#139]
### Describe the feature

The password field in register page is not having hide and show functionality.

Implementing it will improve user satisfaction and experience.

Please assign me this issue under gssoc. Thanks

### Add ScreenShots

![Screenshot 2024-05-16 104147](https://github.com/Note-Vault/Note-Vault/assets/122816988/380567b2-0624-4083-ac06-867c465f0817)

the password field in it is not having side and show functionality.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@piyush-gpt your PR is merged and changes are live on production
