### ISSUE TITLE
Feat: Register page

### ISSUE THREAD

**Issue by anu03k** [Note-Vault/Note-Vault#140]
### Describe the feature

There is no registration page in the project. I would like to create a new one .

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/114494667/811229be-a627-48f5-ba0a-adaec3809fbd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@anu03k  Registration Page already exist in the website
