### ISSUE TITLE
Feat: Add Report button

### ISSUE THREAD

**Issue by ronisarkarexe** [Note-Vault/Note-Vault#141]
### Describe the feature

We can add a report button on the home page. When the user clicks it, they will be redirected to the GitHub issue page.

### Add ScreenShots

![rep](https://github.com/Note-Vault/Note-Vault/assets/76697055/22703cb4-8bdf-470c-a2eb-cf7d639cc4cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@ronisarkarexe  Every user is not familiar with GitHub Instead of this can you create something that will collect the user feedback and store it in DB

**Comment by ronisarkarexe** [comment]
@goyalh4164 yeah sure, we can do this, can you assign me this task?
