### ISSUE TITLE
Feat: Adding Favicon

### ISSUE THREAD

**Issue by harinisayani** [Note-Vault/Note-Vault#150]
### Describe the feature

I want to add favicon to web page.
Please assign me this task.

### Add ScreenShots

![Screenshot (90)](https://github.com/Note-Vault/Note-Vault/assets/143276011/406f4ba4-7c01-424f-859a-04d3e363c396)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#169
