### ISSUE TITLE
Feat: Adding hover effects to links in navbar section

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#152]
### Describe the feature

I want to add hover effects to the links in navbar section.
Please assign me this issue.

### Add ScreenShots

![Screenshot (91)](https://github.com/Note-Vault/Note-Vault/assets/143275265/327d6078-a8a6-4d6b-ba15-31f1f4becf01)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#191
