### ISSUE TITLE
Feat: Adding logo to title in navbar

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#153]
### Describe the feature

I want to add logo to the title in navbar section.
Please assign me this issue.

### Add ScreenShots

![Screenshot (91)](https://github.com/Note-Vault/Note-Vault/assets/143275265/ec5799d4-0b58-4693-ae9d-8ace3149f943)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@harikasayani your PR is merged and changes are live on production
