### ISSUE TITLE
Feat: Adding icons to login page.

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#154]
### Describe the feature

I want to add icons to the login  page.
Please assign me this issue.

### Add ScreenShots

![Screenshot (92)](https://github.com/Note-Vault/Note-Vault/assets/143275265/c103a6e4-b86c-4871-af1d-18f4080f49ae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@harikasayani your PR is merged and changes are live on production
