### ISSUE TITLE
Feat: Making a fixed navbar and adding active sections CSS to it.

### ISSUE THREAD

**Issue by justmirr** [Note-Vault/Note-Vault#161]
### Describe the feature

I'd like to fix the navbar to the top when scrolling through the page and add highlights to the current section like; why us or testimonials.

### Add ScreenShots

![nav](https://github.com/Note-Vault/Note-Vault/assets/75358919/90add59e-b972-40ee-b790-36f7b197c015)
![nav2](https://github.com/Note-Vault/Note-Vault/assets/75358919/a4c27c8f-eb5e-4f24-9e34-2a60f69518af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
under GSSOC'24 contributor
Can you Please assign this issue to me
