### ISSUE TITLE
Fix Navbar

### ISSUE THREAD

**Issue by VaibhavArora314** [Note-Vault/Note-Vault#162]
Navbar breaks into new line
![image](https://github.com/Note-Vault/Note-Vault/assets/84830429/e94d8bd2-e954-4ce8-aecb-dfc838bddac8)

**Comment by Aryan-Shan** [comment]
Hi there ! @Ultimateutkarsh11 I would Like to Work on this issue. Please assign it to me.

I think the Nav- Bar can be improved upon as it is wrapping under a small aspect ratio. Also i can help add Hover animations to the nav links to make it more attractive.

**Comment by Ultimateutkarsh11** [comment]
@Aryan-Shan assigned you the issue, go ahead!

**Comment by Aryan-Shan** [comment]
Thanks a lot @Ultimateutkarsh11 I will start working right away.

**Comment by Aryan-Shan** [comment]
@Ultimateutkarsh11 hi can you please tell me in which directory is the HTML file located? i can't seem to find it anywhere

**Comment by justmirr** [comment]
@Aryan-Shan the content is in ejs files, not html

**Comment by Aryan-Shan** [comment]
@Ultimateutkarsh11 I Have added the nav Bar animations and created a separate pull request for my Improved UI. Please review both the changes.

Thank you.
