### ISSUE TITLE
Enhance Navbar Functionality with Sticky Positioning and Section Highlights

### ISSUE THREAD

**Issue by Ayushk3** [Note-Vault/Note-Vault#163]
Elevate user experience by fixing the navbar at the top during scroll and adding dynamic highlights to active sections like "Why Us" and "Testimonials" for seamless navigation and improved accessibility.
<img width="861" alt="Screenshot 2024-05-17 at 10 40 55 AM" src="https://github.com/Note-Vault/Note-Vault/assets/126401927/f5741161-b32f-41a8-93af-03e22526ac44">
<img width="1278" alt="Screenshot 2024-05-17 at 10 39 33 AM" src="https://github.com/Note-Vault/Note-Vault/assets/126401927/d9114aa1-1a58-4048-8106-7a8afdac6558">

**Comment by Ayushk3** [comment]
Assignment Request:
Please assign this issue to me. I have experience working with the tech stack used in your project and am confident I can implement these enhancements efficiently.

**Comment by Ultimateutkarsh11** [comment]
Someone has already been assigned this issue (Check #161).
