### ISSUE TITLE
Feat: Enhancement of  text color and font in the card's text 

### ISSUE THREAD

**Issue by sahithinandikula** [Note-Vault/Note-Vault#166]
### Describe the feature

The text color and font are not visually appealing. they can be changed to look better. The information in the cards can be more creative

### Add ScreenShots

![WhatsApp Image 2024-05-17 at 13 34 44_c40159e7](https://github.com/Note-Vault/Note-Vault/assets/138794574/7b1487d8-884c-4a71-8bbb-0693c99c3a42)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sahithinandikula** [comment]
@goyalh4164 allow me to contribute to this project.

**Comment by goyalh4164** [comment]
Your PR is Merged and your changes are live on the production
