### ISSUE TITLE
Feat: Improve Navigation Bar Alignment and Color Scheme

### ISSUE THREAD

**Issue by HarsikaKumari** [Note-Vault/Note-Vault#170]
### Describe the feature

**Issue Description:**
The current navigation bar on the Note-Vault website is not properly aligned, and the overall color combination used throughout the website is not visually appealing. These issues negatively impact the user experience and make the application look unprofessional. **As a contributor with experience in EJS, HTML, and JavaScript, I would like to work on improving the alignment of the navigation bar and enhancing the color scheme to create a more modern and user-friendly interface.**

**Proposed Changes:**

1. **Navigation Bar Alignment:** Analyze the existing HTML/CSS code responsible for the navigation bar and make necessary adjustments to ensure proper alignment of the navigation items. This may involve adjusting margins, paddings, or using CSS flexbox or grid layouts.

2. **Color Scheme Improvement:** Conduct research on modern and appealing color combinations that are visually pleasing and enhance readability. Implement a new color scheme throughout the website by updating the CSS styles for various elements such as headings, text, backgrounds, and borders.

**Qualifications:**
I have extensive experience working with EJS, HTML, and JavaScript, as evident from my GitHub profile (https://github.com/HarsikaKumari) and LinkedIn profile (https://www.linkedin.com/in/harsika-kumari). I have successfully completed several projects involving front-end development and UI/UX improvements, demonstrating my ability to enhance the visual appeal and usability of web applications.

**Additional Information:**
Please feel free to provide any additional guidelines, design preferences, or specific requirements you may have for this enhancement. I am open to suggestions and feedback to ensure that the proposed changes align with the project's goals and vision.

By addressing these issues, we can significantly improve the overall user experience and create a more visually appealing and professional-looking website for Note-Vault.

Let me know if you need any further clarification or have additional requirements regarding this issue.

### Add ScreenShots

1. **Navigation Bar:** 
>  ![image](https://github.com/Note-Vault/Note-Vault/assets/147150204/ec537718-ffe7-4614-92ab-a21a6ab80de7)
2. **Color Scheme Improvement:**
> ![image](https://github.com/Note-Vault/Note-Vault/assets/147150204/ac51246d-7cb1-4588-a194-0fd4eccfd856)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
just a piece of advice, try to keep issue descriptions short, clear and to the point. makes it easier for us to quickly assign issues.

as for the navbar, similar issues are already assigned.
as for the color scheme improvement, please explain what color scheme are you planning to use.

**Comment by HarsikaKumari** [comment]
Thank you @VaibhavArora314  for the advice regarding keeping issue descriptions concise and clear. I appreciate the feedback, as it will help me improve my approach to creating effective issue reports in the future.

**Comment by HarsikaKumari** [comment]
The user interface (UI) of the website is not good because there are improper color combinations in some areas (some are dark, some are light, and some are any other color), the text is in red and green, and the color combinations are bad. To improve the UI, I can make the website's color combinations perfect.
