### ISSUE TITLE
Feat:

### ISSUE THREAD

**Issue by Ayushk3** [Note-Vault/Note-Vault#175]
### Describe the feature

I want to enhance user experience by adding an eye button beside the password field that toggles between showing and hiding the password. This feature improves usability and ensures password entry accuracy.

Sir,Please assign me this task.

### Add ScreenShots

<img width="1173" alt="Screenshot 2024-05-18 at 1 54 25 AM" src="https://github.com/Note-Vault/Note-Vault/assets/126401927/d5ade616-f1dc-4900-832d-0c3afcf31a46">
<img width="1196" alt="Screenshot 2024-05-18 at 1 55 18 AM" src="https://github.com/Note-Vault/Note-Vault/assets/126401927/124dfce6-06ef-4f5a-82ce-a6169507a248">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
This issue is already assigned to someone else (Check #139)
