### ISSUE TITLE
Feat:Adding Hamburger button for responsiveness and animation in button

### ISSUE THREAD

**Issue by Ayushk3** [Note-Vault/Note-Vault#177]
### Describe the feature

Add a responsive hamburger button with smooth animations for toggling the navigation menu on smaller screens, ensuring accessibility and a cohesive design. Implement using HTML, CSS, and JavaScript. if the screen size is reduced after a fixed width .

### Add ScreenShots

<img width="573" alt="Screenshot 2024-05-18 at 10 26 05 AM" src="https://github.com/Note-Vault/Note-Vault/assets/126401927/b57198f3-af39-447f-bab7-2dec58e5f2c2">
<img width="296" alt="Screenshot 2024-05-18 at 10 26 34 AM" src="https://github.com/Note-Vault/Note-Vault/assets/126401927/c660205d-178d-42a4-80f7-eccbbf19a70a">
Hamburger Button will look like the above and will turn into ❌ after clicking on this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
sure go ahead
