### ISSUE TITLE
Update Card Design

### ISSUE THREAD

**Issue by VaibhavArora314** [Note-Vault/Note-Vault#187]
Redesign the note card ui, also show creation date and finish date in the card

![image](https://github.com/Note-Vault/Note-Vault/assets/84830429/423eb604-8d0b-4b9d-823c-fc92211f8076)

Also update card design in search results

![image](https://github.com/Note-Vault/Note-Vault/assets/84830429/32c012b1-7da2-4c97-8a68-760726f21b1a)

Make sure both cards look good in dark as well as light mode

**Comment by its-AkshatJain** [comment]
Hello,
I am Akshat , a GSSOC Contributor.
Please assign me this task i can update the card design in your Web App.

**Comment by VaibhavArora314** [comment]
looks good to me, go ahead raise a pr
