### ISSUE TITLE
Update add note card

### ISSUE THREAD

**Issue by VaibhavArora314** [Note-Vault/Note-Vault#189]
Redesign the add note card. make sure it looks good in both dark and light mode. Also link the date fields as they are currently not stored in the database.

![image](https://github.com/Note-Vault/Note-Vault/assets/84830429/f010c033-e2df-4d1c-9317-8b9ecfae5022)

**Comment by Asymtode712** [comment]
@VaibhavArora314 I would like to work on this issue, please assign me

**Comment by Saksham1411** [comment]
@VaibhavArora314 its been 2 weeks and issue is not resolved assign this to me under GSSOC 24. I can enhance the UI of add note card
