### ISSUE TITLE
Update UI of About Us Section

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [Note-Vault/Note-Vault#190]
The current "About Us" section of the website looks bad:

![image](https://github.com/Note-Vault/Note-Vault/assets/95978839/f07749b8-d3e6-4094-89a2-cdd44f58345b)

Changes that need to made:
1. The current font style in the "About Us" section does not match the other fonts used in the website, change it to a decent-looking font.
2. Remove the extra spaces in the "About Us" section.
3. Also, make this section responsive.

**Comment by Dishika18** [comment]
I would like to take this issue. Kindly assign this issue to me.
