### ISSUE TITLE
Redesign the footer of the website

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [Note-Vault/Note-Vault#192]
There is a need for a footer in the website, which displays necessary information with a good UI.
Try designing something like this:
![330132920-857e9fdd-bd6a-4e47-8c1f-76f852f65908](https://github.com/Note-Vault/Note-Vault/assets/95978839/88a696f0-f80e-42e1-841e-8a70ec8025c3)
Note: The above image is only for reference, you can modify it to incorporate your changes.

**Comment by DhayanandhS** [comment]
Hey @Ultimateutkarsh11, I can make the footer more appealing and good looking for all viewers and contributors. 
As of now the footer looks something like this,
![Screenshot 2024-05-19 004910](https://github.com/Note-Vault/Note-Vault/assets/112493275/3a24cbd0-0fbc-4a85-b05d-8e740c89b562)
Which is very much simple and does not look great. So I can make it better and responsive. 

Can you assign me this issue?

**Comment by Ultimateutkarsh11** [comment]
@DhayanandhS sure, go ahead!

**Comment by roushanverma23** [comment]
@goyalh4164 please assign this task, I want to work on this
![gssoc](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137530796/bc19c5b1-a3c9-457f-b0f4-09e916b6b627)

**Comment by Ultimateutkarsh11** [comment]
@roushanverma23 this issue has already been assigned to @DhayanandhS, kindly open a new issue.

**Comment by roushanverma23** [comment]
Okay thankyou

**Comment by DhayanandhS** [comment]
Hey @Ultimateutkarsh11, I have done a footer that seems great for the website.
![Screenshot 2024-05-19 192650](https://github.com/Note-Vault/Note-Vault/assets/112493275/7ff09117-e3fc-4fe9-8f93-3a34dcc8c251)
Should I make a PR?

**Comment by Dishika18** [comment]
If this issue is still open i would like to work on this issue. Please assign still issue to me.
