### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [Note-Vault/Note-Vault#195]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by VaibhavArora314** [comment]
there already exists a pr template in the repository, it was previously in incorrect folder. you can enhance it if you want.

**Comment by suhanipaliwal** [comment]
I would like to update the template and organise it in a better way.
