### ISSUE TITLE
#Testimonials linkedin profile url not propery added

### ISSUE THREAD

**Issue by roushanverma23** [Note-Vault/Note-Vault#198]
### Describe the feature

LinkedIn profile link not added in testimonials section of their respective clients. 

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/137530796/a4033d1f-b844-470a-a76f-3da7a5b37f78)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
what will you add as a link these are just dummy icons
