### ISSUE TITLE
DOC: update deployment link

### ISSUE THREAD

**Issue by alishasingh06** [Note-Vault/Note-Vault#21]
### What's wrong with the existing documentation

The deployment link mentioned in the Readme file is incorrect, it does not redirect to the website. It redirects to the same repository again, kindly provide the correct link

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@alishasingh06 the deployment link is now added in the project's description. you can now update it in the README.md..
Go Ahead!!!

**Comment by alishasingh06** [comment]
sent the pull request, kindly merge
