### ISSUE TITLE
BUG: Doesn't have Round corner

### ISSUE THREAD

**Issue by MuraliDharan7** [Note-Vault/Note-Vault#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The first section does not have the round corner as other sections are having the same but the first one hits different

Please assign this to me under GSSoC'24

![Note_vault second issue](https://github.com/Note-Vault/Note-Vault/assets/130668745/717b8e93-921e-4696-a389-6f55f8b7a963)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
Hi @techmannih
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can fix the bug
Please assign this task to me, GSSOC'24 .
