### ISSUE TITLE
DOC: Improve Folder Structure

### ISSUE THREAD

**Issue by MitulSonagara** [Note-Vault/Note-Vault#22]
### What's wrong with the existing documentation

Existing structure is have only one server.js file which is not good for standard file structure for industry level. In this all the routes and mongoose models are in same files which results in complex access.
I will make the folder structure like 

├── src
│   ├── controller
│   ├── views
│   ├── model
│   ├── index.js

so that all the models will be in one folder, all the routes will be in one folder and controllers like isAuthenticated will be in one folder.

### Add ScreenShots
![image](https://github.com/Note-Vault/Note-Vault/assets/95460188/baf62594-c7c3-4531-bfaf-3cacf11c3c20)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
@MitulSonagara assigned you the issue, go ahead!
