### ISSUE TITLE
Feat: Navbar Elements Misalignment

### ISSUE THREAD

**Issue by dhruv389** [Note-Vault/Note-Vault#221]
### Describe the feature

The elements within the navbar are not properly aligned. This misalignment affects the visual consistency and user experience across different screen sizes and devices.

**Please assign me this issue.**

### Add ScreenShots

![Screenshot 2024-05-20 030852](https://github.com/Note-Vault/Note-Vault/assets/117587892/98079ddd-91b8-48cc-8437-7cf25771be93)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
Run git pull and fetch the latest code, this issue has been resolved.
