### ISSUE TITLE
Feat: Make Home Page Visually Eye-Catching

### ISSUE THREAD

**Issue by dhruv389** [Note-Vault/Note-Vault#224]
### Describe the feature

**Description:**
The home page requires visual enhancements to make it more eye-catching. Currently, the font size is excessively large, and the image in the home section does not look good, negatively affecting the overall appearance.

**Steps to Reproduce:**
1. Open the application in a web browser.
2. Navigate to the home page.
3. Observe the font size and the image in the home section.

**Expected Behavior:**
The home page should have an appealing design with appropriately sized fonts and high-quality, relevant images. The overall layout should be visually attractive and engaging.

**Actual Behavior:**
- The font size on the home page is too large, making the text overwhelming.
- The image in the home section appears low-quality or poorly placed, detracting from the visual appeal.

### Add ScreenShots

![Screenshot 2024-05-20 032711](https://github.com/Note-Vault/Note-Vault/assets/117587892/031559e7-6099-460f-8aa3-c1a3df2b4ef5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
@dhruv389 The home page shown in the screenshot is the old one, run git pull and fetch the latest code.
If you can further enhance the home page do let me know.

**Comment by dhruv389** [comment]
@Ultimateutkarsh11 ,

But the Home page  still looking  same as above my screen shot in **your website link**. and if i wrong then please send me updated version website link .so i can give contribution😊.

**Comment by VaibhavArora314** [comment]
![image](https://github.com/Note-Vault/Note-Vault/assets/84830429/8d12dd99-aae7-4c5c-a174-be4c45e71800)
