### ISSUE TITLE
Feat: Improve UI of landing page

### ISSUE THREAD

**Issue by Caliber-Ruchi** [Note-Vault/Note-Vault#23]
### Describe the feature

As the UI is so bold in nature . I want to make it eye appealing as well as the size of the text doesn't seems good. 
Also the cards in the client section need some improvement.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/128621040/71a84e5c-374f-49e2-9406-274f4a603e7b)
![image](https://github.com/Note-Vault/Note-Vault/assets/128621040/e67c821b-9b4f-439d-83db-d554641cf385)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by Yuvraj960** [comment]
@goyalh4164 Please assign this issue to me under GSSoC24. I will implement this.

**Comment by Rishitatripathi** [comment]
I would like to work on this issue, Please assign it to me under GSSOC 2024

**Comment by harshcodesit** [comment]
Hi @techmannih
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by techmannih** [comment]
hey @harshcodesit 
this project has not assigned me

**Comment by harshcodesit** [comment]
> hey @harshcodesit this project has not assigned me, i am not a mentor for this project

ok sir

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by harshcodesit** [comment]
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by kaali001** [comment]
Hey @VaibhavArora314 , this issue have been opened for a long time , and still it isn't completed,  assign me this issue, sop that I can start working on it , I have already made the about section of this project  #@https://github.com/Note-Vault/Note-Vault/pull/283#issue-2317190870 and you can rely on my work.
