### ISSUE TITLE
Feat: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [Note-Vault/Note-Vault#231]
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

![Close Old Iss](https://github.com/Note-Vault/Note-Vault/assets/115717746/eb33c00c-89cf-4b58-b6cd-f54da793e53a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@VaibhavArora314 @goyalh4164 please assign me this issue under gssoc'24

**Comment by VaibhavArora314** [comment]
how will this work? will it close all old issues after sometime or something else?

**Comment by VaibhavArora314** [comment]
looks good to me, go ahead with 30 days as the time of inactivity after which it closes the issue
