### ISSUE TITLE
Feat: Adding new feature for organization of notes priority wise

### ISSUE THREAD

**Issue by Chelseasingla1** [Note-Vault/Note-Vault#24]
### Describe the feature

I would like to add feature where one can add notes priorities like if someone wants to note down their tasks or want to highlight the note if it is more important for reminding them.

### Add ScreenShots

Something like this:
![image](https://github.com/Note-Vault/Note-Vault/assets/129886894/608d226a-38c7-4177-a0d6-f07b0bb7ce83)

Or like this:
![image](https://github.com/Note-Vault/Note-Vault/assets/129886894/5ff033ba-f8ad-41da-91ca-c440919943a6)

Keeping in one place same type of notes

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24

**Comment by VaibhavArora314** [comment]
ok, so you are saying user can create categories to segregate notes?

**Comment by Chelseasingla1** [comment]
> ok, so you are saying user can create categories to segregate notes?

@VaibhavArora314  Yes or maybe categorise it by giving different colors

**Comment by Chelseasingla1** [comment]
> ok, so you are saying user can create categories to segregate notes?

Thanks for assigning!!!
