### ISSUE TITLE
Feat: Improving Edit feature of Note

### ISSUE THREAD

**Issue by Ansh-Garg22** [Note-Vault/Note-Vault#240]
### Describe the feature

When we click on "Edit Note," there is no "Back" option. Additionally, when the update box appears, it is positioned just above the notes. This issue can be fixed by moving the edit page to another location, which will also improve the UI of the webpage.

Moreover, when we add a date in the edit section, it is not being added to the note. We can fix this issue on both the backend and the frontend.

Hey @Ultimateutkarsh11, please assign this issue to me. I will work on it and fix it as soon as possible.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/127920945/e7bbb5b6-a90e-4113-893a-1eeed7608153)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Ultimateutkarsh11  I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.

**Comment by Ansh-Garg22** [comment]
Hey @VaibhavArora314,

I have resolved the issue. I updated the "Update Note" and "Add Note" features to appear as popups, which blur the background for a better UI appearance. Additionally, I updated the backend to support date updates. Please review the PR and let me know if anything requires.
