### ISSUE TITLE
Feat: Implementing Google Auth

### ISSUE THREAD

**Issue by Ansh-Garg22** [Note-Vault/Note-Vault#241]
### Describe the feature

We can implement Google authentication for the login process, allowing users to sign in directly with their Google accounts. This feature, commonly seen on many websites, will enhance our website's user experience.

Hey @Ultimateutkarsh11, please assign this task to me. I will work on it and implement this feature as soon as possible.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/127920945/3bcd5f13-83ec-4d47-9ad7-84cd8c9474fe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Ultimateutkarsh11  I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine. I have a prior experience of using firebase and google authentication.

**Comment by AnanyaJain25** [comment]
hey @goyalh4164 @VaibhavArora314 can you assign me this issue if its still pendiing ? I have recently implemented forget password functionality in your project.

**Comment by VaibhavArora314** [comment]
@Ansh-Garg22 are you working on this?

**Comment by Ansh-Garg22** [comment]
Yes, actually I am working on #240 issue it's finally merged and will work on this now.
