### ISSUE TITLE
Feat: Improve UI for Close (X) Button on Note Input Box

### ISSUE THREAD

**Issue by Saanvi26** [Note-Vault/Note-Vault#244]
### Describe the feature

Improvement to the UI for the close (X) button on the note input box that appears after clicking the "Add Note" button. Enhancing the design and functionality of this button will provide a more intuitive and user-friendly experience.
After clicking the "Add Note" button, the close (X) button appears to close the note input box. However, the current design of the button may not be immediately clear or easy to use for some users.

### Add ScreenShots

<img width="654" alt="Screenshot 2024-05-21 at 11 47 10 PM" src="https://github.com/Note-Vault/Note-Vault/assets/129958210/b2cf02b7-9b3a-4e12-9ced-a714f05eabb1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Ultimateutkarsh11  I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.
