### ISSUE TITLE
Feat: Functional "Why Us" Link in Navbar

### ISSUE THREAD

**Issue by Saanvi26** [Note-Vault/Note-Vault#246]
### Describe the feature

The "Why Us" link in the navigation bar currently does not lead to any destination. Suggest linking this to a dedicated "Why Us" page or section .

### Add ScreenShots

<img width="552" alt="Screenshot 2024-05-22 at 12 56 35 AM" src="https://github.com/Note-Vault/Note-Vault/assets/129958210/908e6457-df36-4fef-bed2-8952441d8469">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saanvi26** [comment]
@Ultimateutkarsh11  Can you assign this to me ?

**Comment by masterboy376** [comment]
Hello @Ultimateutkarsh11  I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.

**Comment by Saanvi26** [comment]
Hey  @Ultimateutkarsh11 @VaibhavArora314  @goyalh4164 , 
Could you explain exactly what should be included in the " why us " section ?

**Comment by VaibhavArora314** [comment]
Hey @Saanvi26 , you don't need to update why us section, a separate issue, and PR #298  already exists for it. You simply need to add a link for it in the navbar.
