### ISSUE TITLE
Feat: Dark/Light Mode Switcher

### ISSUE THREAD

**Issue by thevijayshankersharma** [Note-Vault/Note-Vault#25]
### Describe the feature

Is your feature request related to a problem? Please describe.
Users often prefer different visual themes based on their preference or environmental conditions. However, many websites and applications lack the option to switch between dark and light modes, leading to discomfort for users in low-light settings or causing eye strain.

Describe the solution you'd like
Implement a dark/light mode switcher that allows users to toggle between different visual themes seamlessly. This feature should provide users with the flexibility to choose between dark and light modes based on their preference or environment.

Describe alternatives you've considered
One alternative is manually adjusting the brightness or contrast settings on the device, but this can be cumbersome and doesn't provide the same level of flexibility as a dedicated dark/light mode switcher.

Additional context
Integrating a dark/light mode switcher enhances user experience and accessibility, providing a more comfortable viewing experience for users in various lighting conditions.

### Add ScreenShots

After assigning the task I will share you the screenshots how it can be.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Sure, go ahead.

**Comment by thevijayshankersharma** [comment]
@VaibhavArora314 Hey, I have some doubt about the project how can we communicate ?

**Comment by VaibhavArora314** [comment]
You can message in the project channel in #projects-intro in the discord server.
