### ISSUE TITLE
Feat: Ask confirmation before deleting the note

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Note-Vault/Note-Vault#252]
### Describe the feature

When user clicks on the delete button of a specific note, it directly deleting the note. If user mistakenly click on that button, entire note will be deleted. It is not a good user experience. So before deleting the note we can ask a confirmation like asking are you sure to delete ''topic of the note' note?

Kindly please assign this issue to me to add this feature.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/139672976/78b995f8-6500-452c-adf9-4c7a80ce8e57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Omkar-Sonawane-23 I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.
