### ISSUE TITLE
BUG: Navbar is not responsive

### ISSUE THREAD

**Issue by prasukjain07** [Note-Vault/Note-Vault#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When switch to phone mode, navbar is not properly responsive

![image](https://github.com/Note-Vault/Note-Vault/assets/115997785/a5b51984-a224-44a7-b59a-415847f5f583)

Please assign this issue to me under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Omkar-Sonawane-23 I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.

**Comment by VaibhavArora314** [comment]
a pr is already raised for the same
