### ISSUE TITLE
Feat: Add Pricing Section for Premium Features

### ISSUE THREAD

**Issue by AkshitGarg24** [Note-Vault/Note-Vault#256]
### Describe the feature

This issue addresses the implementation of a pricing section within the project. It's essential to introduce a premium tier with exclusive offerings to enhance users' note-taking experience. The pricing section will serve as a gateway for users to access these premium features.

### Add ScreenShots

1.  Introduce a "Pricing" button in the navigation bar.

![Navigation](https://github.com/Note-Vault/Note-Vault/assets/153659573/32fcce4c-1794-4fce-806c-10b0cffc0437)

2. Upon clicking this button, a new page will open, displaying various plans with their corresponding features. An attached image provides an example of how this page will appear.

![Price](https://github.com/Note-Vault/Note-Vault/assets/153659573/c09cac20-20e1-4751-99f7-a7637d6524f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
I dont think this feature is needed currently but this can be worked upon in future.
