### ISSUE TITLE
BUG: Resolving testimonials section

### ISSUE THREAD

**Issue by AnanyaJain25** [Note-Vault/Note-Vault#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sizing of block and dicisions is inappropriate due to which if you take cursor around icons screen will start trembling.

https://github.com/Note-Vault/Note-Vault/assets/136808696/d78d08e0-a200-46e4-95ef-a16173416686

Here alignment is improper content is going out of boundary. All over improving UI
![Screenshot 2024-05-23 175953](https://github.com/Note-Vault/Note-Vault/assets/136808696/0726a3c7-9cbc-44ec-802f-3ea4ba7a0683)
![Screenshot 2024-05-23 180016](https://github.com/Note-Vault/Note-Vault/assets/136808696/b827640e-d568-4522-abc9-90e44a2a5ea0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
A pr is already opened for navbar, so except navbar you can work on other parts.

**Comment by Devansh1508** [comment]
please assign me this issue under GSSOC
