### ISSUE TITLE
Feat: ADDING FORGET PASSWORD FEATURE

### ISSUE THREAD

**Issue by AnanyaJain25** [Note-Vault/Note-Vault#260]
### Describe the feature

We can add forget password functionality while logging in .
Please assign me this issue

### Add ScreenShots

![Screenshot 2024-05-23 181314](https://github.com/Note-Vault/Note-Vault/assets/136808696/46d436d2-6d79-45c2-8df6-162fc6cde616)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by VaibhavArora314** [comment]
hey @AnanyaJain25 , how are u planning to implement the forgot password feature? will u send a reset link via email?

**Comment by AnanyaJain25** [comment]
> hey @AnanyaJain25 , how are u planning to implement the forgot password feature? will u send a reset link via email?

Yes @VaibhavArora314 will be using nodemailer module for the same. A reset link will be shared via mail to user , link will comprise of the unique reset token which will ensure authorised access of the link and then password can be reset.

**Comment by VaibhavArora314** [comment]
Sure go ahaed
