### ISSUE TITLE
BUG: OVERLAPS POST REGISTERING ACCOUNT

### ISSUE THREAD

**Issue by AnanyaJain25** [Note-Vault/Note-Vault#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-23 181957](https://github.com/Note-Vault/Note-Vault/assets/136808696/3e2b0622-c72b-406e-987c-72f75c1aafe5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by AnanyaJain25** [comment]
hey @goyalh4164 please assign this issue to me
