### ISSUE TITLE
Feat: Added FAQs page

### ISSUE THREAD

**Issue by dhruv8433** [Note-Vault/Note-Vault#267]
### Describe the feature

@Note-Vault

we can add another route for FAQ's 
where all basic questions of this website present with it's answer

### Add ScreenShots

something like this
![image](https://github.com/Note-Vault/Note-Vault/assets/114583978/923ae533-f7d5-46b1-930d-407133910577)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
dont create a seperate route for this, rather create a new ejs file and import it as partial like header and footer in the home page

**Comment by dhruv8433** [comment]
@VaibhavArora314 ok
