### ISSUE TITLE
BUG: Redesign Footer

### ISSUE THREAD

**Issue by dhruv8433** [Note-Vault/Note-Vault#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Note-Vault

check this out
![image](https://github.com/Note-Vault/Note-Vault/assets/114583978/aae6b5df-574f-4c72-9d2e-6013a952db7c)

Footer is so simple we can multiple links of particular route

something like this
![image](https://github.com/Note-Vault/Note-Vault/assets/114583978/9faaba12-a20d-4997-83bf-5c36cdfa409c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
a pr is already opened for the same
