### ISSUE TITLE
Feat: Favicon

### ISSUE THREAD

**Issue by tat-tvam-asii** [Note-Vault/Note-Vault#27]
### Describe the feature

I would like to add favicon to the website

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/143332267/bdaf5adb-964e-45d8-94aa-89bef2145e69)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#169
