### ISSUE TITLE
BUG: Misaligned Text on "About this Website" Page and inappropriate image used.

### ISSUE THREAD

**Issue by kaali001** [Note-Vault/Note-Vault#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description:
The text on the "About this Website" page is not aligned properly, leading to a disjointed and unprofessional appearance. The text block appears misaligned relative to the image and other elements on the page.

### Steps to Reproduce:

1. Navigate to the "About this Website" page.
2. Observe the alignment of the text content relative to the image and other page elements.

### Expected Behavior:

The text content should be properly aligned with the image and other elements on the page, providing a cohesive and aesthetically pleasing layout.

### Actual Behavior:

The text content is misaligned, causing a disorganized appearance.

### Screenshots:
![image](https://github.com/Note-Vault/Note-Vault/assets/115466381/e6965cff-9e15-44c9-a2bd-4d8c544b911e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
so you want to simply align the text to left side?

**Comment by kaali001** [comment]
Hey @VaibhavArora314  ,  Actually I want align the texts from both side by using css property `justify`, And also I would like to add a new png for this section which will be more visually appealing. below is some given png, let me know if any suits well -  

1.
![undraw_Bookshelves_re_lxoy](https://github.com/Note-Vault/Note-Vault/assets/115466381/3f651750-8372-4e07-9020-45b0ed034742)

2.
![undraw_Taking_notes_re_bnaf](https://github.com/Note-Vault/Note-Vault/assets/115466381/2060cfac-2948-483d-acb3-0f0f2f96366b)


3.
![undraw_Process_re_gws7](https://github.com/Note-Vault/Note-Vault/assets/115466381/9a3b8f8e-b499-4481-a874-b2d36302ec30)

**Comment by VaibhavArora314** [comment]
All the images look good to me, use the one which fits best in both dark and light mode.

**Comment by kaali001** [comment]
Ok, so I would say 2nd is good , but I have to edit it for dark mode also.

**Comment by kaali001** [comment]
Hey @VaibhavArora314 , It takes to much time , and I fixed many things of about section, and make complete new look. see the PR, if possible can you change the label of difficulty ?
