### ISSUE TITLE
Add details to Why Choose NoteVault

### ISSUE THREAD

**Issue by diya05arora** [Note-Vault/Note-Vault#272]
### What's wrong with the existing documentation

The existing document does not have any information under the heading Why Choose NoteVault. 

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/145909573/a708fee8-5c75-4728-b45d-617305dedf7d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
similar issues already raised #266
