### ISSUE TITLE
Improve the navigation bar of the website

### ISSUE THREAD

**Issue by diya05arora** [Note-Vault/Note-Vault#273]
### What's wrong with the existing documentation

the current navigation bar's elements are not aligned perfectly. 

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/145909573/61f6a87b-fb5e-49e4-b473-897b73dff2ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somyagupta05** [comment]
Hello sir,
I would like to contribute inorder to improve the navigation bar of the website.

**Comment by VaibhavArora314** [comment]
you are seeing this because navbar is not responsive, a similar pr already is raised for the same
