### ISSUE TITLE
BUG: No email validation 

### ISSUE THREAD

**Issue by Sailesh3000** [Note-Vault/Note-Vault#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i am able to signup and login while giving incorrect email without domain it only checks for '@
![image](https://github.com/Note-Vault/Note-Vault/assets/126142666/db6e8ec0-eb1b-47e2-982d-b3d414c24eff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
so you will send a verification link to the email? using nodemailer or something else?

**Comment by VaibhavArora314** [comment]
add a regex validation for it
