### ISSUE TITLE
BUG: Fixing "What Our Client Say" Section

### ISSUE THREAD

**Issue by AkshitGarg24** [Note-Vault/Note-Vault#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text in the "What Our Clients Say" section is misaligned.

https://github.com/Note-Vault/Note-Vault/assets/153659573/758eee2d-e86e-4788-87b3-41571336c8a7

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#259

**Comment by bchetule** [comment]
Is this issue closed?
