### ISSUE TITLE
BUG:  form validation for login/signup  page

### ISSUE THREAD

**Issue by reshamsai150** [Note-Vault/Note-Vault#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Note-Vault/Note-Vault/assets/164533685/1c9fdf48-eb8c-43bd-b12c-96f77973553d)
In the login/signup page form validation is not provided  for email

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#275
