### ISSUE TITLE
Feat:Changing why choose note-vault section

### ISSUE THREAD

**Issue by YadlaMani** [Note-Vault/Note-Vault#282]
### Describe the feature

The current info in this section is not good and can be improved by adding better divs with good info and icons

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/133841094/c38234ed-a1d4-4772-b034-1a0c815182fc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Similar issues already exist for this section
