### ISSUE TITLE
BUG: Social media icons are not visible in teh footer

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Note-Vault/Note-Vault#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Note-Vault/Note-Vault/assets/125277258/144d2348-fbdf-4f93-a4bd-f97f1386b230)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
this problem is due to the testimonials section and an issue is already raised for it
