### ISSUE TITLE
BUG: overlapping buttons, and unresponsive congratulation message

### ISSUE THREAD

**Issue by Devansh1508** [Note-Vault/Note-Vault#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Describe the bug
- overlapping buttons appears after clicking on search button
- unresponsive congratulation message.

## Screen shot
- overlapping buttons
<img width="1087" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/160311808/a39b5e6c-1e54-4a5c-9d77-079776a7daba">

- congratulation message after registering 
<img width="322" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/160311808/0d3f72ef-97f0-4001-b0de-f8c6381a5a2a">

<img width="1049" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/160311808/085482be-67c9-4220-a9db-148e85c17f47">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#261 is same as this and as for navbar, the current looks somewhat different from this
![image](https://github.com/Note-Vault/Note-Vault/assets/84830429/556be660-9c23-46c0-af43-7b52c8bd9258)

**Comment by Devansh1508** [comment]
after updating the forked repository.
this navbar is there, whenever you search for any note and click on search button you will get this navbar
<img width="1068" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/160311808/1b478779-18f6-4993-8128-d11aa9755dee">
