### ISSUE TITLE
BUG: blipping text while hovering over the icons

### ISSUE THREAD

**Issue by Devansh1508** [Note-Vault/Note-Vault#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While hovering over the icons this issue occurs.

https://github.com/Note-Vault/Note-Vault/assets/160311808/81b90149-ee08-4d0e-851b-e8c2d808258b

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
#259
