### ISSUE TITLE
Add Home Page Navigation Button to Login and Register Pages

### ISSUE THREAD

**Issue by krishnas005** [Note-Vault/Note-Vault#29]
### Describe the feature

Currently, the login and register pages lack a direct navigation button to return users to the home page. Adding a home page navigation button on these pages would enhance user experience by providing a convenient way for users to return to the main page without having to use the browser's back button or manually type the URL.

### Add ScreenShots

![Screenshot 2024-05-12 181536](https://github.com/Note-Vault/Note-Vault/assets/117625683/3bae91ff-27a9-4c65-b7e4-f791bdb07d45)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by krishnas005** [comment]
@VaibhavArora314 I want to work on this assign this to under GSSOC'24

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
