### ISSUE TITLE
Feat: new todo cards

### ISSUE THREAD

**Issue by Devansh1508** [Note-Vault/Note-Vault#291]
### Describe the feature

The current Todo card design appears outdated. I propose implementing a new card layout in the UI to modernize the website's appearance.

### Add ScreenShots

- current design
<img width="350" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/160311808/27d93bb0-2fef-4e2b-a896-3e9cca895f4e">

- proposed design
<img width="314" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/160311808/0f12a300-6db4-4754-8a2f-ccb2af53a0e2">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
@Devansh1508 The current design goes better with the theme of the website as compared to the proposed one, you can try something different which is sleek, modern and matches the overall UI of the website
