### ISSUE TITLE
Fix Font Sizes for Improved UI Consistency

### ISSUE THREAD

**Issue by krishnas005** [Note-Vault/Note-Vault#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current UI suffers from inconsistent font sizes, leading to a disjointed and unpolished appearance. Standardizing font sizes across the application will enhance visual appeal, readability, and overall user experience. 

![Screenshot 2024-05-12 182102](https://github.com/Note-Vault/Note-Vault/assets/117625683/13c841e8-36d1-4439-826d-4def8ba37f80)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by krishnas005** [comment]
@VaibhavArora314  I want to work on this assign this to me under GSSOC'24

**Comment by ritu713** [comment]
Hey! If this issue is still open and not worked upon, I'd like to work on this as part of GSSOC '24
