### ISSUE TITLE
Add CONTRIBUTING.md File

### ISSUE THREAD

**Issue by krishnas005** [Note-Vault/Note-Vault#31]
### What's wrong with the existing documentation

I propose adding a CONTRIBUTING.md file to the repository to provide contributors with guidelines and instructions for contributing to the project. This file will serve as a reference for newcomers and existing contributors, outlining the contribution process, coding standards, and other relevant information necessary for effective collaboration.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by krishnas005** [comment]
@VaibhavArora314 I want to work on this, assign this to me under GSSOC'24

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.
