### ISSUE TITLE
Feat: Align Navbar perfectly 

### ISSUE THREAD

**Issue by zalabhavy** [Note-Vault/Note-Vault#314]
### Describe the feature

I want to do changes in Navbar that is not perfectly align as existing website.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/126322584/4d16cbbe-c996-48a3-bef4-fd951d6a8afc)
I will make them align correctly.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ved8290** [comment]
Can this issue be assigned to me for gssoc '24

**Comment by zalabhavy** [comment]
No , I am working on that.

**Comment by Maheshwari-Love** [comment]
@gopalepic can you please assign this to me?

**Comment by AbhinaySngh** [comment]
@Ultimateutkarsh11 please assign me this issue, abhi thik kr k deta hu ,i'm gssoc'24 contributor.

**Comment by Ultimateutkarsh11** [comment]
@zalabhavy are you working on this issue?

**Comment by zalabhavy** [comment]
@Ultimateutkarsh11 Already done this 3 days ago 
 See PR:  Navbar Align In One Raw #316 
Please check it and merge !!
