### ISSUE TITLE
Feat: File conversion

### ISSUE THREAD

**Issue by Cralsic123** [Note-Vault/Note-Vault#32]
### Describe the feature

Would provide an inbuilt feature to convert file types i.e. from pdf to pptx and such.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/101086033/117c76be-96fe-4c40-adf3-99b561f9ca0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Cralsic123** [comment]
I would like to contribute here and solve this issue @VaibhavArora314

**Comment by VaibhavArora314** [comment]
the project is a note-taking application, why would it need file conversion?

**Comment by Cralsic123** [comment]
@VaibhavArora314 once the notes are taken, wouldn't the user want to download it in the form of pdf, pptx or any other format for easy handling and vice versa for uploading it and then taking notes on the predefined notes?

**Comment by goyalh4164** [comment]
@Cralsic123 can you do something like this such that user can download the pdf of it's entire notes present in its account in one go..

**Comment by Cralsic123** [comment]
Yes that is the thing I was talking about.
Can I try @goyalh4164?
Please assign me this issue.
