### ISSUE TITLE
Feat: Improving UI/UX of add notes feature

### ISSUE THREAD

**Issue by Saksham1411** [Note-Vault/Note-Vault#325]
### Describe the feature

Need improvements in the Add note feature

1. Close button is too small 
    I will move it to the right corner and enhance the user experience
2. The input does not follow the equal spacing between each other and some headings are too big and some are small which decreases the user experience

Assign me this under gssoc24 I can fix and enhance the user experience and improve the UI by changing color scheme and font sizing

### Add ScreenShots

![add notes ui ux fixes](https://github.com/Note-Vault/Note-Vault/assets/101385720/4f1f52e7-b14d-4c5c-bbb4-07d194c0cd17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kaali001** [comment]
Hey @Saksham1411 , the UI of website have been changed, but its not not visible on the website,  because its not updated, check the issue once by cloning it on local machine.
