### ISSUE TITLE
Anchor tag styling

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Note-Vault/Note-Vault#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Note-Vault/Note-Vault/assets/125277258/c6a13720-4c02-4c9f-a259-bd9908c8a379)
anchor tag is not styled properly

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Implement anchor tag styling for all the anchors in the website. Closing #35
