### ISSUE TITLE
Feat:login page is not looking proper in mobile view 

### ISSUE THREAD

**Issue by SalehaTabassum** [Note-Vault/Note-Vault#34]
### Describe the feature

As we can see that the input text fields are overflowing so I want to fix it 
Please assign this issue to me under GSSOC 2024 and add necessary labels to it 
@u

### Add ScreenShots

![Screenshot_2024-05-12-19-13-19-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Note-Vault/Note-Vault/assets/169278740/8f639cf7-259e-4c33-921e-06d8fe4ff335)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by SalehaTabassum** [comment]
@goyalh4164  when I got this issue assigned there was the problem in login page ...but now the login page has been completely changed....
![Screenshot_2024-05-15-14-04-20-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Note-Vault/Note-Vault/assets/169278740/2751875d-a3e9-4246-9956-a48644afeeea)
 Now what shall I do ?
