### ISSUE TITLE
Logo anchor tag and font styling

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Note-Vault/Note-Vault#35]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

![image](https://github.com/Note-Vault/Note-Vault/assets/125277258/ad63d6a2-358f-4cea-a433-b62f6ded6edd)
it is not a good-looking UI for the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Same as #33
