### ISSUE TITLE
Adding social media icons

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Note-Vault/Note-Vault#36]
### Describe the feature

social media icons in the footer of the website

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/125277258/471b7a56-2f5a-420e-98c8-4f5ed72da71a)
here

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by alishasingh06** [comment]
@goyalh4164 please assign this task to me

**Comment by GDGouravDey** [comment]
I would like to work on this issue. Please do assign me if you want.
