### ISSUE TITLE
BUG: Adding Hover to why choose section.

### ISSUE THREAD

**Issue by MuraliDharan7** [Note-Vault/Note-Vault#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hover effect for the below section is not there.
![image](https://github.com/Note-Vault/Note-Vault/assets/130668745/d5fb3c66-848b-44d7-bfac-a97c395eb79b)

The hover effect should be added in that section. I can add the same. Please assign this to me under GSSoC'24. Add relevant labels into it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by deepxnshiiii** [comment]
hey there, I can add the hover effect, please assign this to me with label gssoc

**Comment by MuraliDharan7** [comment]
@goyalh4164  has this section already edited? (for which I created this issue)
