### ISSUE TITLE
BUG: Dark mode button is moving in signup and login up page

### ISSUE THREAD

**Issue by Ketanop321** [Note-Vault/Note-Vault#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In login and signup page dark mode button is not moving on clicking on it 

https://github.com/Note-Vault/Note-Vault/assets/146806880/896b32e5-d4b0-43c5-a532-4f4fc218884a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gamerking177** [comment]
@goyalh4164 how to connect mongoDB with your project

**Comment by Gamerking177** [comment]
@goyalh4164 can you give a screenshot of your .env file plss
