### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by deepxnshiiii** [Note-Vault/Note-Vault#376]
### Describe the feature

The page is not designed to be responsive.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/118647735/92017187-46a6-4e25-9bc6-e6612f2f99f5)
![image](https://github.com/Note-Vault/Note-Vault/assets/118647735/83f3f84c-9d4d-436c-b643-ff7748c607b3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by deepxnshiiii** [comment]
> Hey! I am thinking that the whole design can use a good design. Its ok if i take it up?

Naah! i am sorry but i wanna do this

**Comment by IshadP** [comment]
Can we collab ? I would like to help in any shape or form possible!

**Comment by deepxnshiiii** [comment]
is that possible?
