### ISSUE TITLE
Create a about page

### ISSUE THREAD

**Issue by Ridhima10** [Note-Vault/Note-Vault#38]
### Describe the feature

I would like to add a about page in the website. It will allow users to engage more with your website since it will give a description about your website

### Add ScreenShots

![Screenshot 2024-05-12 201655](https://github.com/Note-Vault/Note-Vault/assets/85826117/3d27358f-789a-4acd-802f-954a621b3719)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshcodesit** [comment]
Hi @techmannih
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design an amazing About us page to the website
Please assign this task to me, GSSOC'24 .
