### ISSUE TITLE
Better Readme.md file

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Note-Vault/Note-Vault#4]
In the readme.md file no tech stack defined
and many more things need to write i can write all the things 
assign it to me 
#gssoc2024

**Comment by SumitKumar-17** [comment]
@kshavp  I want to work on this ssue. Can you assign this issue to me under GSSoc'24?

**Comment by prajwal9773** [comment]
I can add better readme file, which is more describable, assign it to me

**Comment by NiranjanSharma-edu** [comment]
Hello Sir, I can make this readme file as per all the requirements with all the proper documentation so, assign this to me.

**Comment by VaibhavArora314** [comment]
@RamakrushnaBiswal also add some screenshots of the working project
