### ISSUE TITLE
Feat: improvement in footer 

### ISSUE THREAD

**Issue by 05priyanshu** [Note-Vault/Note-Vault#41]
### Describe the feature

The alignment and styling in the footer is not good i will improve it 

### Add ScreenShots

![Screenshot 2024-05-12 204637](https://github.com/Note-Vault/Note-Vault/assets/118009761/87718df5-3e20-4cc0-931d-fecf765ddd9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhinaySngh** [comment]
@VaibhavArora314 Please assign me this issue.
