### ISSUE TITLE
Feat: Improve Navbar

### ISSUE THREAD

**Issue by hars-21** [Note-Vault/Note-Vault#44]
### Describe the feature

Improving Navbar will be a good idea for good user experience and seamless user navigation.

### Add ScreenShots

![Screen Shot 2024-05-12 at 8 56 14 PM](https://github.com/Note-Vault/Note-Vault/assets/144909381/6cec052b-e268-4314-9ce1-8415648ff115)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SanaAzeem512** [comment]
please assign this issue under gssoc24

**Comment by BhumikaRahwani** [comment]
Hi!! I am Bhumika Rahwani, contributor in GSSoC'24. I would like to address this issue and make the respective changes.

**Comment by goyalh4164** [comment]
@hars-21 your PR is merged and changes are live now
