### ISSUE TITLE
Feat: Add scroll to top 

### ISSUE THREAD

**Issue by hars-21** [Note-Vault/Note-Vault#45]
### Describe the feature

Adding scroll to top button for user to smoothly navigate to top of the page.
Adding smooth scroll effect for ux.

### Add ScreenShots

![Screen Shot 2024-05-12 at 8 58 27 PM](https://github.com/Note-Vault/Note-Vault/assets/144909381/6ff93a22-889e-4118-8121-d499cd385a6a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GDGouravDey** [comment]
I would like to work on this issue, as I find it fairly easy to handle. Please do assign me this issue.

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
