### ISSUE TITLE
Feat: Redesign home page 

### ISSUE THREAD

**Issue by hars-21** [Note-Vault/Note-Vault#460]
### Describe the feature

Currently the Ui of website look very poor. 
I want to enhance the ui so that user has active participation.
I will put a particular theme that will improve design and also the placement of section. 

### Add ScreenShots

![Screen Shot 2024-06-06 at 10 19 08 PM](https://github.com/Note-Vault/Note-Vault/assets/144909381/8ba35f1a-9f4b-4dd7-a014-c6c7870c2809)
![Screen Shot 2024-06-06 at 10 19 14 PM](https://github.com/Note-Vault/Note-Vault/assets/144909381/84441a9b-9b94-4636-8217-d938e13ced4e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by drick-infinity** [comment]
can you assign this issue to me as I learned MERN full stack development I made a lot of design home page can you assign this iisue to me under GSSOC'24

**Comment by drick-infinity** [comment]
I use various tools using tailwind css
