### ISSUE TITLE
BUG: Welcome message & 'Your Notes' section misaligned on user page after login

### ISSUE THREAD

**Issue by shivanjalikarande** [Note-Vault/Note-Vault#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After logging in on user page, there is noticeable space between navbar & welcome message as well as your notes section. Currently these elements are placed at bottom of page but they should present just after the navbar. I will fix this issue by aligning all elements to correct positions. 
![Screenshot (1572)](https://github.com/Note-Vault/Note-Vault/assets/145892931/efa2c942-b442-46b0-8bea-2952d6ae2696)
![Screenshot (1573)](https://github.com/Note-Vault/Note-Vault/assets/145892931/75e9cc29-39ae-4324-8059-8215ba611298)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@shivanjalikarande notes are also not visible.. fix that also if you are able to do that then this issue will get merged with level3 label
