### ISSUE TITLE
Feat: Change logo 

### ISSUE THREAD

**Issue by Ridhima10** [Note-Vault/Note-Vault#47]
### Describe the feature

I would like to change the logo of your website. I will not change it completely but enhance it so that your website will be more attractive

### Add ScreenShots

![Screenshot 2024-05-12 221319](https://github.com/Note-Vault/Note-Vault/assets/85826117/dab96f9e-068f-4cd8-b667-a5a527c57eed)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
