### ISSUE TITLE
BUG: Notes are not visible on the dashboard

### ISSUE THREAD

**Issue by goyalh4164** [Note-Vault/Note-Vault#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Notes are not visible on the dashboard even when user add a new note it is not visible.. kindly fix this

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by atharvarekhawar** [comment]
Hello @goyalh4164 , I would like to contribute to this issue , please assign this to me.

**Comment by Sneha0019** [comment]
Hello, @goyalh4164 I can contribute on this issue. As it seems an issue of backend I can complete this task. Please assign it to me under GSSOC'24

**Comment by devanshi00** [comment]
Hello, @goyalh4164 
 I want to work on it can you please assign it me. I have already worked on such projects and my technical skills include Node , React, Tailwind Css, Bootstrap ,Javascript, MongoDB.

**Comment by Manaswini123456** [comment]
Hello, @goyalh4164 I am MERN Stack developer, kindly assign me with this issue, so that I can provide my insights.
