### ISSUE TITLE
Make visible "password less than 8 characters" error in the login page

### ISSUE THREAD

**Issue by itssarvani394** [Note-Vault/Note-Vault#476]
### Describe the feature

In the login page, on entering password less than 8 characters, it redirects to a page in JSON format. Would like to correct it, making it display on the login page near the section where password is entered.

### Add ScreenShots

It shows this, would like to correct this

![image](https://github.com/Note-Vault/Note-Vault/assets/129776752/e99a7623-7330-48c1-be45-140c1f1ec574)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by UtkarshBirla28** [comment]
@goyalh4164  
Can you please assign me this issue under #gssoc

**Comment by UtkarshBirla28** [comment]
@goyalh4164 it's been 2 weeks and it hasn't been solved yet assign me this issue i will resolve it ASAP
