### ISSUE TITLE
Feat: Improve the UI of notes

### ISSUE THREAD

**Issue by Saksham1411** [Note-Vault/Note-Vault#48]
### Describe the feature

Problem
The current user interface (UI) of the notes feature appears outdated and could benefit from a modern design update. This includes improving aesthetics, user experience, and visual appeal.

Proposed Solution
Revamp the UI of the notes section to reflect a more contemporary and user-friendly design. This enhancement aims to incorporate modern UI/UX principles, such as cleaner layouts, intuitive navigation, and visually appealing elements.

### Add ScreenShots

![Screenshot 2024-05-12 221917](https://github.com/Note-Vault/Note-Vault/assets/101385720/d3152169-d86e-4f7a-ace4-b832d4047fe9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham1411** [comment]
As a GSsoc'24 contributor. I want to address this issue. I request you to assign this to me @Ultimateutkarsh11

**Comment by VaibhavArora314** [comment]
#51
