### ISSUE TITLE
BUG: Contact us section is not visible in dark mode

### ISSUE THREAD

**Issue by ayushrskiaa** [Note-Vault/Note-Vault#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Contact us section is not visible in dark mode

![image](https://github.com/Note-Vault/Note-Vault/assets/130389607/489dd6c0-e093-43a9-97ff-382666a875db)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
Please assign it to me.
thank you

**Comment by Tanishka023** [comment]
Hey! Please assign this to me; I can fix this issue easily
