### ISSUE TITLE
Feat: hover effect

### ISSUE THREAD

**Issue by Shreyaa173** [Note-Vault/Note-Vault#493]
### Describe the feature

want to add hover effect

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/144673309/54c5d439-55ea-4728-b912-6ceeff0daef2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HareRamDwivedi** [comment]
Please assign me this issue under GSSOC24

**Comment by biplabmahato** [comment]
i can add a hover effect to this. please assign this to me
