### ISSUE TITLE
Adding hover effect .

### ISSUE THREAD

**Issue by supriyagaut** [Note-Vault/Note-Vault#502]
![Screenshot 2024-06-09 231214](https://github.com/Note-Vault/Note-Vault/assets/141560711/88ce53f6-6ccc-4c35-85e1-5ff7a761cf3d)
please assign me this issue

**Comment by dfghjkbd** [comment]
please assign me this issue

**Comment by biplabmahato** [comment]
i can add a beautiful hover effect to the cards . please assign this to me
