### ISSUE TITLE
Feat: Hover effect to footer

### ISSUE THREAD

**Issue by chaanakyaaM** [Note-Vault/Note-Vault#509]
### Describe the feature

The website would look even more attractive if hover effect is added to the links present in the footer.

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/131477601/fc105ef9-e1c1-4558-8f59-291b8fc8c18f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.

**Comment by biplabmahato** [comment]
please assign this i can help you out
