### ISSUE TITLE
Enhancement in the Contact page with borders.

### ISSUE THREAD

**Issue by agrwal697** [Note-Vault/Note-Vault#512]
### Describe the feature

I think if the Contact section had border-bottom in every text item so it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the level and label of GSSOC.

### Add ScreenShots

Before:

![image](https://github.com/Note-Vault/Note-Vault/assets/128716726/1a12cb30-dc75-459c-98ce-a65b602c4371)

After:

![image](https://github.com/Note-Vault/Note-Vault/assets/128716726/279b7f48-6508-4769-8307-c5fb671a90fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.
