### ISSUE TITLE
BUG:while enabling the dark mode the respective section is bluring as shown below

### ISSUE THREAD

**Issue by Harish-2003** [Note-Vault/Note-Vault#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Note-Vault/Note-Vault/assets/76206815/58a7ebe9-45c4-48a0-8cd8-684dd33af3b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.
