### ISSUE TITLE
Feat: Changing navbar color

### ISSUE THREAD

**Issue by harinisayani** [Note-Vault/Note-Vault#524]
### Describe the feature

I have observed that navbar color is not suitable to the webpage. I want to change the color of the navbar.
I am GSSOC'24 contributor.
Please assign me this issue.

### Add ScreenShots

![Screenshot (15)](https://github.com/Note-Vault/Note-Vault/assets/143276011/3b3cd324-a87e-48d2-bd73-315cc1ca06df)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by imergs** [comment]
I am interested in solving this issue
