### ISSUE TITLE
Feat: Adding FAQ link in navbar

### ISSUE THREAD

**Issue by harinisayani** [Note-Vault/Note-Vault#525]
### Describe the feature

I have observed that FAQ link is not present in navbar section. I want to add it in the navbar section.
Please assign me this issue.
I am GSSOC'24 contributor.
Please assign me this issue.

### Add ScreenShots

![Screenshot (15)](https://github.com/Note-Vault/Note-Vault/assets/143276011/32d2a185-a818-4be1-adcb-1d75885fd0e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by imergs** [comment]
I think FAQ link is not working in navbar section. I will be happy to resolve this issue in the navbar section.
Please assign me this issue.
I am GSSOC'24 contributor.
