### ISSUE TITLE
BUG: Changing contact us page color in dark mode

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I observed that while the webpage is in dark mode, contact us page is unable to visible.
![Screenshot (18)](https://github.com/Note-Vault/Note-Vault/assets/143275265/ac48291d-c9e0-49ec-8570-bf90053388ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dfghjkbd** [comment]
please assign me this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.
