### ISSUE TITLE
BUG: Search text not visible

### ISSUE THREAD

**Issue by sarthakmisal** [Note-Vault/Note-Vault#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When typed inside searchbox text is not visible

![image](https://github.com/Note-Vault/Note-Vault/assets/142015424/14075b07-a38e-4407-b7d9-08666870c38c)

But it should be visible
![image](https://github.com/Note-Vault/Note-Vault/assets/142015424/5d2488c8-4665-44f9-bcab-122306ac6895)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SCR01** [comment]
Please assign me this issue

**Comment by sarthakmisal** [comment]
@pallavisavant please assign me this issue
