### ISSUE TITLE
Feat: Adding a Date in notes

### ISSUE THREAD

**Issue by SamarthUrane** [Note-Vault/Note-Vault#54]
### Describe the feature

Implement a feature to include dates in notes, enhancing organization and clarity for users. This addition facilitates better time management and reference within the note-taking system. 
Kindly assign me this task for GSSOC. Thank you for your support.

### Add ScreenShots

![Screenshot 2024-05-13 022217](https://github.com/Note-Vault/Note-Vault/assets/108013711/7886ed0a-9233-40eb-8f1c-5e191efba161)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Ok, so u want to add finish date in notes?

**Comment by SamarthUrane** [comment]
My idea is to add creation timeline so user can know when he/she created that note. Adding a finish date is also a good idea.

**Comment by VaibhavArora314** [comment]
Make finish date optional
