### ISSUE TITLE
BUG:Lack of responsive design in Home page

### ISSUE THREAD

**Issue by KARANSINGH34951** [Note-Vault/Note-Vault#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upon reviewing the website's responsiveness and text readability, I've identified areas for improvement to enhance the overall user experience.
<img width="960" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/137412876/d9b6135e-ac47-4755-abcf-ea036280b847">

<img width="960" alt="image" src="https://github.com/Note-Vault/Note-Vault/assets/137412876/8e8eb8da-d27c-4ae3-b72c-1b1fe9758c57">

I can fix that assign me this issue under GSS0C 2024

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Amitesh-Mishra-AM** [comment]
### Can you assign me the issue , I would like to work on it.

**Comment by anshdeep0504** [comment]
Hi!! I am Anshdeep singh, contributor in GSSoC'24. I would like to address this issue and make the respective changes.
