### ISSUE TITLE
Feat:  adding hovering effect for this cards

### ISSUE THREAD

**Issue by reshamsai150** [Note-Vault/Note-Vault#553]
### Describe the feature

When you add hover effects to cards, they come alive with interactivity and visual flair. Users will feel like they’re interacting with magical artifacts! Here are a few ways to achieve this:

### Add ScreenShots

![image](https://github.com/user-attachments/assets/49d14441-3c6e-4640-b55f-02797194ec8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by reshamsai150** [comment]
assign this issue to me

**Comment by Simran903** [comment]
Can I work on this issue?
