### ISSUE TITLE
Feat: Add Newsletter Subscription to Footer

### ISSUE THREAD

**Issue by lovelymahor** [Note-Vault/Note-Vault#554]
### Describe the feature

Our website currently lacks a newsletter subscription option in the footer. Adding this feature will help us engage with our audience and keep them updated with our latest news and offers.

Required Features:

Email input field
Subscribe button
Confirmation message

### Add ScreenShots

![Screenshot (251)](https://github.com/user-attachments/assets/db0bc4f9-372b-4bd6-a625-907489a9f0fd)

Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Simran903** [comment]
Can i work on this issue?
