### ISSUE TITLE
BUG: Notification style 

### ISSUE THREAD

**Issue by 05priyanshu** [Note-Vault/Note-Vault#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After adding and deleting the notes the notification style is not good looking 
![Screenshot 2024-05-13 102501](https://github.com/Note-Vault/Note-Vault/assets/118009761/b8e9b36b-4a8b-4339-8397-12eecee5918e)
![image](https://github.com/Note-Vault/Note-Vault/assets/118009761/3844e240-d4f4-45d2-b654-5e968dbb3713)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Amitesh-Mishra-AM** [comment]
I would like to work on the issue, if you want please assign it to me.

**Comment by bchetule** [comment]
Checking if this issue is resolved  ? if not, Can this issue be assigned to me for gssoc ? @VaibhavArora314
