### ISSUE TITLE
BUG: Register Button Visibility Issue 

### ISSUE THREAD

**Issue by ishap11** [Note-Vault/Note-Vault#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,
This is Isha Prajapati.
The "Register" button is not fully visible in either light or dark theme, which affects user interaction. I am eager to contribute under GSSoC'24 to improve our website’s functionality and user experience. Please assign this task to me.
Thank you!

![Screenshot 2024-08-08 120054](https://github.com/user-attachments/assets/236b4eb4-a74c-433a-a40a-51736d01dfc7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Simran903** [comment]
Can i work on this issue?
