### ISSUE TITLE
Better and responsive frontend

### ISSUE THREAD

**Issue by callmeVAMP** [Note-Vault/Note-Vault#6]
Frontend can be improved with better responsiveness and more user friendly

**Comment by VaibhavArora314** [comment]
Sure, go ahead.

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by callmeVAMP** [comment]
My end sem exams are till 21st. Can I start working on this after that?
