### ISSUE TITLE
Feat: Improving the UI of login and Registration page and making responsive

### ISSUE THREAD

**Issue by Khanishsuresh** [Note-Vault/Note-Vault#65]
### Describe the feature

Adding a related background colour to your login page as well as the registration page
Making the UI more user-friendly to access the login and registration page
Then improve the responsiveness of the website, which would help ur project to work even on mobile 

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/136162512/28ec3d86-b943-4df9-bc1f-2aa6c6ce43cf)

![image](https://github.com/Note-Vault/Note-Vault/assets/136162512/5087a6f2-4024-47ea-b53c-14b69035f111)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
Hii @VaibhavArora314 ,

As a GSSOC'24 contributor, I would like to contribute 

Would u please assign me work on this issue under GSSOC'24?

**Comment by VaibhavArora314** [comment]
#19 and #20 already exist
Please check before raising issues

**Comment by Khanishsuresh** [comment]
Hii @VaibhavArora314 ,

I have a reference screen shot , just look this login page and let me know

![image](https://github.com/Note-Vault/Note-Vault/assets/136162512/22ebd7fa-6e18-4ef7-9c11-68fe87662e46)

**Comment by VaibhavArora314** [comment]
@Khanishsuresh it sure does look good but assigning it to you will be unfair for the other person who is also working on the same. Feel free to raise any other issue after checking the issue list.
