### ISSUE TITLE
BUG: Updated or adding of note info is not accurate.

### ISSUE THREAD

**Issue by Amitesh-Mishra-AM** [Note-Vault/Note-Vault#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Note-Vault/Note-Vault/assets/86422382/7413d006-5641-4d4d-b4f3-99040589f4d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Isn't this the same as #56 ?

**Comment by Amitesh-Mishra-AM** [comment]
## Yes it's same, sorry I didn't saw, i will close the issue as it is already listed.
