### ISSUE TITLE
Feat:Improving UI of login page 

### ISSUE THREAD

**Issue by paridhi1509** [Note-Vault/Note-Vault#67]
### Describe the feature

The Login page doesn't look appealing to the eyes and i would like to work on it by aligning it more according the basic idea of Note-Vault by adding more images, animations, effects and also improving the overall alignment of the page. 
The page currently doesn't relate to the overall idea of Note Vault. 

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/146311385/56d95628-744f-426e-a8c2-d6b8ca6bf906)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VaibhavArora314** [comment]
Same as #19
