### ISSUE TITLE
DOC: Adding favicon icon

### ISSUE THREAD

**Issue by Khanishsuresh** [Note-Vault/Note-Vault#68]
### What's wrong with the existing documentation

the web doesn't have a icon

### Add ScreenShots

![image](https://github.com/Note-Vault/Note-Vault/assets/136162512/662c8893-f7e1-4e69-97af-7ad4d5ea6230)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
hii @VaibhavArora314 ,

i would like to create a new designed logo for ur web which would be related
would u assign me this issue under the respective lables?

**Comment by vignesh-0512** [comment]
HI, i would like to work on this issue by adding proper favicon to the website so i would request to assign me this issue under gssoc'24.

**Comment by VaibhavArora314** [comment]
same as #27
