### ISSUE TITLE
Feat: Adding the user feedback section 

### ISSUE THREAD

**Issue by Khanishsuresh** [Note-Vault/Note-Vault#69]
### Describe the feature

by adding the feedback section , it will help us make the changes according to the users

by doing so, we can understand the users request . so we can update the web according to the costomers

### Add ScreenShots

adding the feedback section in the nav bar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
Hii @VaibhavArora314 ,

i would like to work on this issue .
Would u please assign me this issue under GSSOC and the respective lables?

**Comment by Khanishsuresh** [comment]
Hii @VaibhavArora314 ,

i would like to work on this issue .
Would u please assign me this issue under GSSOC and the respective lables?

**Comment by VaibhavArora314** [comment]
so you are planning to add a seperate page for it or integrate it as a section in home page?

**Comment by Khanishsuresh** [comment]
@VaibhavArora314 yeah I am planning to add a separate page , where the users can give there feedback about the webpage.
but the link to move will be added in the header section, as a feedback icon

**Comment by VaibhavArora314** [comment]
Sure go ahead
