### ISSUE TITLE
Feat: Dark/Light theme change

### ISSUE THREAD

**Issue by Khanishsuresh** [Note-Vault/Note-Vault#70]
### Describe the feature

making the website as per the user's wishes by changing the dark/light mode of the website

### Add ScreenShots

adding the dark/light mode icon in the nav section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
Hii @VaibhavArora314 ,

i would like to add this feature to your project, which makes the user-interactive and helpful 
Would u please assign this issue to me under GSSOC and the respective lables

**Comment by vignesh-0512** [comment]
Hi, i would like to work on this project, I have strong knowledge in html,css and javascript so i would request you to assign me this issue under GSSOC'24.

**Comment by VaibhavArora314** [comment]
same as #25
