### ISSUE TITLE
Feat: home page improvement

### ISSUE THREAD

**Issue by harinisayani** [Note-Vault/Note-Vault#72]
### Describe the feature

developing home page more attractive. I use HTML, CSS and JavaScript to make it beautiful.

### Add ScreenShots

![Screenshot (2)](https://github.com/Note-Vault/Note-Vault/assets/143276011/f6a6b63d-66c8-4914-9b13-eb6fa99517bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushnegi007** [comment]
hi @goyalh4164 can you also assign me this issue
