### ISSUE TITLE
Feat: Changing font

### ISSUE THREAD

**Issue by harinisayani** [Note-Vault/Note-Vault#73]
### Describe the feature

Font in the web page is not attractive and not looking good. I want to improve it.

### Add ScreenShots

![Screenshot (2)](https://github.com/Note-Vault/Note-Vault/assets/143276011/4d2cd9dc-c189-43c8-b1d4-c36c98f24aea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
i am from GSSOC and will help in making the font look more attractive for the UX, please assign this task to me.
