### ISSUE TITLE
BUG: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Note-Vault/Note-Vault#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ApurvaBasule** [comment]
hey @pankaj-bind you still working on it ? i'm open to work on it @goyalh4164 please assign it to me.
