### ISSUE TITLE
Feat: Improving login page

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#75]
### Describe the feature

I'll improve the login page using HTML, CSS and JavaScript.

### Add ScreenShots

![Screenshot (3)](https://github.com/Note-Vault/Note-Vault/assets/143275265/b7c370cb-95a1-4393-97c3-a4e200d11889)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by goyalh4164** [comment]
Login page is updated to completely new design already.. check the latest deployed website
