### ISSUE TITLE
Feat: Creating navbar

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#76]
### Describe the feature

I observed that navbar is not attractive. I want to make it attractive and clearly visible using HTML, CSS and JavaScript.

### Add ScreenShots

![Screenshot (4)](https://github.com/Note-Vault/Note-Vault/assets/143275265/ff9de2a1-3e06-43f3-b090-524a59d9e9d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by Kalyan9064** [comment]
I would like to work on this issue.
Please Assign me this task.

**Comment by Ultimateutkarsh11** [comment]
Someone is already working on this issue (Issue #46), so closing it as of now.
