### ISSUE TITLE
Feat: Adding Logo

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#82]
### Describe the feature

I will add logo beside the Note vault title in navbar.

### Add ScreenShots

![Screenshot (82)](https://github.com/Note-Vault/Note-Vault/assets/143275265/78ecdadd-77d4-4205-a134-7ddb83a41538)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
Someone is already working on the navbar (Issue #46), so closing it as of now.
