### ISSUE TITLE
Feat: Enhancing "why choose note vault page"

### ISSUE THREAD

**Issue by harikasayani** [Note-Vault/Note-Vault#83]
### Describe the feature

I want to improve the "why choose note vault" page to look more attractive.

### Add ScreenShots

![Screenshot (83)](https://github.com/Note-Vault/Note-Vault/assets/143275265/e50c3684-9921-476c-b292-1f78a0a02514)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@harikasayani Thanks for contributing your changes are live now
