### ISSUE TITLE
DOC: CODE OF CONDUCT.md file 

### ISSUE THREAD

**Issue by anglerfishlyy** [Note-Vault/Note-Vault#84]
### What's wrong with the existing documentation

Its not properly STYLED.

### Add ScreenShots

![Screenshot (55)](https://github.com/Note-Vault/Note-Vault/assets/163823908/3b528459-e3d2-4898-b3f5-ead1303d3e40)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ultimateutkarsh11** [comment]
The screenshot is not visible can you reupload it?

**Comment by VaibhavArora314** [comment]
#145
