### ISSUE TITLE
Feat: Adding About Section

### ISSUE THREAD

**Issue by Dishika18** [Note-Vault/Note-Vault#91]
### Describe the feature

Your About Section is a valuable digital asset and one of your website's most frequently visited pages. I noticed that about section is missing in your website. I can make an impressive About Section using HTML and CSS.
Plz assign me this issue under GSSoC'24.

### Add ScreenShots

Here is just a SAMPLE ABOUT SECTION for your website. After getting assign for the issue i'll make it look good and impressive.
![Screenshot 2024-05-14 144221](https://github.com/Note-Vault/Note-Vault/assets/152963337/5ff223bb-fbbc-4e12-b5a3-54f4bc1548e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by goyalh4164** [comment]
@Dishika18 Your PR is merged
