### ISSUE TITLE
Design : Change background for all pages in the project

### ISSUE THREAD

**Issue by ritu713** [Note-Vault/Note-Vault#96]
The current background and UI is pretty simple.
I'd like to add some more professional and coordinated colours.

The following colour palette is what I'm proposing to use : 
![image](https://github.com/Note-Vault/Note-Vault/assets/124053206/88b679ba-9e3c-4ff7-8726-02f529bfaba4)

Colour palette can be changed as per your preferance.

**LIST:**
No existing issue
Will follow Code of Conduct
Working under GSSOC
Interested in working on this issue

**Comment by goyalh4164** [comment]
Your PR is merged

**Comment by ritu713** [comment]
Good to know :)
